Africode_Demo_Collaboration/app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from config import Config

db = SQLAlchemy()

def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)

    db.init_app(app)

    from app.routes import bp as main_bp
    app.register_blueprint(main_bp)

    with app.app_context():
        # Importing models here if necessary
        # from app import models  # Uncomment and adjust as needed

        # Create database tables (if needed)
        # db.create_all()  # Avoid calling create_all() in production

        return app

Africode_Demo_Collaboration/app/routes.py
from flask import Blueprint, render_template, render_template, request, redirect, url_for, flash


bp = Blueprint('main', __name__)

@bp.route('/')
def index():
    return render_template('index.html')

@bp.route('/fitness')
def fitness():
    return render_template('fitness.html')

@bp.route('/fitness/<section>')
def fitness_section(section):
    # Assuming 'section' can be 'cardio', 'strength', 'flexibility', 'balance', 'core', etc.
    return render_template('fitness.html', section=section)


@bp.route('/nutrition')
def nutrition():
    return render_template('nutrition.html')

@bp.route('/about')
def about():
    return render_template('about.html')

@bp.route('/about/<section>')
def about_section(section):
    # Assuming 'section' can be 'our_mission', 'founders_story', etc.
    return render_template('about.html', section=section)

@bp.route('/testimonials')
def testimonials():
    return render_template('testimonials.html')

@bp.route('/contact')
def contact():
    if request.method == 'POST':
        name = request.form['name']
        email = request.form['email']
        message = request.form['message']
        # Handle form submission
        flash('Thank you for your message! We will get back to you soon.')
        return redirect(url_for('main.contact'))
    return render_template('contact.html')

Africode_Demo_Collaboration/app/templates/about.html
{% extends 'base.html' %}

{% block title %}About Us - FitPulse{% endblock %}

{% block content %}
<div class="container">
    <h1>About FitPulse</h1>

    {% if section == 'our_mission' %}
    <section id="our_mission">
        <h2>Our Mission</h2>
        <p>At FitPulse, our mission is to inspire and empower individuals to achieve their fitness and wellness goals through innovative training, personalized guidance, and a supportive community. We believe that fitness is a journey, and we are committed to providing the resources, motivation, and expertise to help our clients succeed.</p>
        <p>We aim to:</p>
        <ul>
            <li>Promote a holistic approach to health and wellness that encompasses physical fitness, nutrition, and mental well-being.</li>
            <li>Offer state-of-the-art fitness programs and cutting-edge technology to enhance the workout experience.</li>
            <li>Create a welcoming and inclusive environment where everyone feels valued and motivated to reach their full potential.</li>
            <li>Foster a community of like-minded individuals who support and encourage each other on their fitness journeys.</li>
            <li>Continuously innovate and improve our services to meet the evolving needs of our clients and the fitness industry.</li>
        </ul>
    </section>
    {% endif %}
    {% if section == 'Founders story' %}
    <section id="Founders story">
        <h2>Founders story</h2>
        <section id="founders_story">
            <h2>Founder's Story</h2>
            <p>FitPulse was born out of the passion and vision of our founders, Gladwel Chelang'at and Naomy Cherono. Growing up in different parts of Kenya, both Gladwel and Naomy always had a keen interest in fitness and wellness. Despite facing numerous challenges, they pursued their dreams with unwavering determination.</p>
            
            <p>Gladwel's journey began with her own personal transformation. Struggling with weight issues and health problems, she decided to take control of her life. Through dedication and hard work, she adopted a healthy lifestyle, losing over 50 pounds and overcoming her health challenges. This transformation inspired her to help others achieve their fitness goals.</p>
            
            <p>Naomy, on the other hand, had always been active in sports and physical activities. Her background in sports science and nutrition, combined with her passion for helping others, made her a perfect partner for Gladwel. Together, they envisioned creating a holistic fitness platform that would make fitness accessible and enjoyable for everyone.</p>
            
            <p>In 2015, Gladwel and Naomy founded FitPulse with a simple mission: to make fitness accessible and enjoyable for everyone. They started with a small fitness studio, offering personalized training and nutrition plans. Their holistic approach and genuine care for their clients quickly gained recognition, and FitPulse began to grow.</p>
            
            <p>Under their leadership, FitPulse has evolved into a comprehensive fitness and wellness platform, offering a wide range of services including online coaching, fitness classes, and wellness workshops. The FitPulse team has helped thousands of clients transform their lives and achieve their health goals.</p>
            
            <p>Gladwel and Naomy's story is a testament to the power of perseverance, passion, and the belief that anyone can achieve their dreams with the right support and guidance. Their commitment to helping others and their vision for a healthier world continue to drive the success and growth of FitPulse.</p>
    </section>
    {% endif %}


    {% if section == 'our_team' %}
    <section id="our_team">
        <h2>Our Team</h2>
        <div class="team-member">
            <h3>Naomy Cherono</h3>
            <div class="image">
                <img class="pics-1" src="{{ url_for('static', filename='images/naomi.jpeg') }}">
            </div>
            <p>Email: naomycherono892@gmail.com</p>
            <p>Phone: (254) 794461554</p>
        </div>

        <div class="team-member">
            <h3>Gladwel Chelangat</h3>
            <div class="image">
                <img class="pics-2" src="{{ url_for('static', filename='images/gladwell.jpeg') }}">
            </div>
            <p>Email: chelangatgladwel9@gmail.com</p>
            <p>Phone: (254) 707162940</p>
        </div>
    </section>
    {% endif %}

    {% if section == 'our_achievements' %}
    <section id="our_achievements">
        <h2>Our Achievements</h2>
        <ul>
            <li>Helped thousands of clients achieve their fitness goals.</li>
            <li>Received recognition for outstanding customer satisfaction.</li>
            <li>Featured in prominent fitness publications or media outlets.</li>
            <li>Won awards for innovation in fitness technology or training methods.</li>
            <li>Expanded our services to reach a global audience.</li>
            <li>Established partnerships with leading fitness brands or organizations.</li>
            <li>Hosted successful fitness events or workshops.</li>
            <li>Received positive feedback and testimonials from satisfied clients.</li>
            <li>Contributed to the community through fitness education or charity initiatives.</li>
            <li>Maintained a high standard of professional certifications and qualifications.</li>
        </ul>
    </section>
    {% endif %}

    {% if section == 'future_goals' %}
    <section id="future_goals">
        <h2>Future Goals</h2><section id="future_goals">
            <h2>Future Goals</h2>
            <p>At FitPulse, we are committed to continuously evolving and enhancing our services to meet the ever-changing needs of our clients. Our future goals are centered around expanding our reach, improving our offerings, and making a lasting impact on the global fitness community. Here are some of our key future goals:</p>
            <ul>
                <li><strong>Expand Our Online Presence:</strong> We aim to enhance our digital platform to provide more interactive and personalized fitness programs. This includes launching a mobile app that offers customized workout plans, nutrition advice, and virtual coaching sessions.</li>
                <li><strong>Open New Fitness Centers:</strong> As part of our growth strategy, we plan to open new state-of-the-art fitness centers in various cities. These centers will offer a wide range of fitness classes, top-notch equipment, and wellness services.</li>
                <li><strong>Innovate with Technology:</strong> We are investing in cutting-edge fitness technology to provide our clients with the best possible experience. This includes incorporating virtual reality workouts, AI-driven fitness analytics, and advanced wearable devices.</li>
                <li><strong>Promote Wellness Education:</strong> We believe that knowledge is key to a healthy lifestyle. We will be launching a series of educational workshops, webinars, and online courses to educate our community on fitness, nutrition, and overall well-being.</li>
                <li><strong>Strengthen Community Engagement:</strong> Our goal is to build a strong, supportive community both online and offline. We will host more community events, fitness challenges, and social gatherings to foster a sense of belonging and mutual support among our members.</li>
                <li><strong>Global Outreach:</strong> We are working towards expanding our services internationally, bringing our unique approach to fitness and wellness to a global audience. This includes forming strategic partnerships with international fitness brands and organizations.</li>
                <li><strong>Environmental Responsibility:</strong> We are committed to making our operations more sustainable. Our future initiatives include reducing our carbon footprint, using eco-friendly materials, and promoting environmental awareness within our community.</li>
            </ul>
            <p>These goals reflect our dedication to continuous improvement and our commitment to helping individuals lead healthier, happier lives. We are excited about the future and look forward to achieving these milestones with the support and enthusiasm of the FitPulse community.</p>
        </section>
        
        
    </section>
    {% endif %}
</div>
{% endblock %}

Africode_Demo_Collaboration/app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}My Website{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
</head>
<body>
    <header>
        <div class="site-name">
            <h1>Fit<span class="pulse">Pulse</span></h1>
        </div>
        <nav class="navbar">
            <ul>
                <li><a class="nav-links" href="{{ url_for('main.index') }}">Home</a></li>
                <li class="dropdown">
                    <a href="#" class="dropbtn">Fitness <i class="fa fa-caret-down"></i></a>
                    <div class="dropdown-content">
                        <a href="{{ url_for('main.fitness_section', section='introduction') }}">Introduction to Fitness</a>
                        <a href="{{ url_for('main.fitness_section', section='cardio') }}">Cardiovascular Exercises</a>
                        <a href="{{ url_for('main.fitness_section', section='strength_training') }}">Strength Training</a>
                        <a href="{{ url_for('main.fitness_section', section='flexibility') }}">Flexibility Exercises</a>
                        <a href="{{ url_for('main.fitness_section', section='balance') }}">Balance Exercises</a>
                        <a href="{{ url_for('main.fitness_section', section='core') }}">Core Exercises</a>
                        <a href="{{ url_for('main.fitness_section', section='fitness-tips') }}">Fitness tips</a>
                        <a href="{{ url_for('main.fitness_section', section='expert-fitness-tips') }}">Expertise Tips</a>
                    </div>
                </li>
                <li><a class="nav-links" href="{{ url_for('main.nutrition') }}">Nutrition</a></li>
                <li class="dropdown">
                    <a href="#" class="dropbtn">About <i class="fa fa-caret-down"></i></a>
                    <div class="dropdown-content">
                        <a href="{{ url_for('main.about_section', section='our_mission') }}">Our Mission</a>
                        <a href="{{ url_for('main.about_section', section='founders_story') }}">Founder's Story</a>
                        <a href="{{ url_for('main.about_section', section='our_team') }}">Our Team</a>
                        <a href="{{ url_for('main.about_section', section='our_achievements') }}">Our Achievements</a>
                        <a href="{{ url_for('main.about_section', section='future_goals') }}">Future Goals</a>
                    </div>
                </li>
                <li><a class="nav-links" href="{{ url_for('main.testimonials') }}">Testimonials</a></li>
                <li><a class="nav-links" href="{{ url_for('main.contact') }}">Contact</a></li>
            </ul>
        </nav>
    </header>
    <main>
        {% block content %}{% endblock %}
    </main>
   
</body>
</html>

Africode_Demo_Collaboration/app/templates/contact.html
{% extends 'base.html' %}

{% block title %}Contact Us{% endblock %}

{% block content %}
<h1>Contact Us</h1>
<div class="contact-section">
    <p>If you have any questions, suggestions, or feedback, feel free to reach out to us through the form below or through our social media channels.</p>

    <form action="{{ url_for('main.contact') }}" method="post">
        <div class="form-group">
            <label for="name">Name</label>
            <input type="text" id="name" name="name" required>
        </div>
        <div class="form-group">
            <label for="email">Email</label>
            <input type="email" id="email" name="email" required>
        </div>
        <div class="form-group">
            <label for="message">Message</label>
            <textarea id="message" name="message" rows="5" required></textarea>
        </div>
        <button type="submit" class="btn">Send Message</button>
    </form>

    <div class="contact-info">
        <h2>Our Office</h2>
        <p>Cooperative bank<br>3rd Floor</p>
        <p> Our Email: <a href="naomicherono892@gmail.com">naomicherono892@gmail.com</a></p>
        <p>Phone: (254)707162940</p>
    </div>
</div>
{% endblock %}

Africode_Demo_Collaboration/app/templates/fitness.html
{% extends 'base.html' %}

{% block title %}Fitness{% endblock %}

{% block content %}
<div class="container">
    <h1>Fitness</h1>

    {% if section == 'introduction' %}
    <section id="introduction">
        <h2>Introduction to Fitness</h2>
        <div class="content-container">
            <div class="text-column">
                <p>Welcome to the Fitness section. Here you'll find tips, exercises, and guides to help you stay fit and healthy.</p>
                <p>Regular physical activity and exercise are essential for maintaining good health and well-being.</p>
                <p>Whether you're aiming to improve your cardiovascular endurance, build strength, or enhance flexibility, incorporating fitness into your daily routine can have numerous benefits.</p>
                <p>Fitness not only helps you achieve physical goals but also contributes to mental and emotional well-being.</p>
                <p>It can boost your mood, reduce stress levels, and improve sleep quality.</p>
                <p>Getting started with fitness can be as simple as taking a brisk walk, cycling, or performing bodyweight exercises at home.</p>
                <p>It's important to choose activities that you enjoy and can sustain over time.</p>
                <p>Remember, consistency is key to seeing results. Start gradually, listen to your body, and gradually increase the intensity and duration of your workouts as your fitness level improves.</p>
            </div>
            <div class="intro">
                <img src="{{ url_for('static', filename='images/fitness1_image.jpeg') }}" alt="Fitness Image">
            </div>
        </div>
    </section>
    {% endif %}

    {% if section == 'cardio' %}
    <section id="cardio">
        <h2>Cardiovascular Exercises</h2>
        <div class="exercise">
            <div class="content-container">
                <div class="text-column">
                    <p>Cardiovascular exercises elevate your heart rate and improve overall cardiovascular health.</p>
                    <p>Examples include running, swimming, cycling, and jumping rope.</p>
                </div>
                <div class="image exercise-images">
                    <img class="exercise-image" src="{{ url_for('static', filename='images/running_image.jpeg') }}">
                    <img class="exercise-image" src="{{ url_for('static', filename='images/swimming_image.jpeg') }}">
                    <img class="exercise-image" src="{{ url_for('static', filename='images/cycling_image.jpeg') }}">
                    <img class="exercise-image" src="{{ url_for('static', filename='images/skipping_image.jpeg') }}">
                </div>
            </div>
        </div>
    </section>
    {% endif %}

    {% if section == 'strength' %}
    <section id="strength">
        <h2>Strength Training</h2>
        <div class="exercise">
            <div class="content-container">
                <div class="text-column">
                    <p>Strength training exercises build muscle strength, endurance, and power.</p>
                    <p>Examples include weightlifting, resistance band exercises, and bodyweight exercises like push-ups and squats.</p>
                    <p>Benefits of strength training include:</p>
                    <ol class="benefits">
                        <li>Increased muscle mass and metabolism.</li>
                        <li>Improved bone density and reduced risk of osteoporosis.</li>
                        <li>Enhanced functional strength for daily activities.</li>
                        <li>Improved posture and joint stability.</li>
                    </ol>
                </div>
                <div class="image exercise-images">
                    <img class="exercise-image" src="{{ url_for('static', filename='images/weightlifting_image.jpeg') }}">
                    <img class="exercise-image" src="{{ url_for('static', filename='images/squat_image.jpeg') }}">
                    <img class="exercise-image" src="{{ url_for('static', filename='images/pushup_image.jpeg') }}">
                </div>
            </div>
        </div>
    </section>
    {% endif %}

    {% if section == 'flexibility' %}
    <section id="flexibility">
        <h2>Flexibility Exercises</h2>
        <div class="exercise">
            <div class="content-container">
                <div class="text-column">
                    <p>Flexibility exercises improve range of motion and prevent injury.</p>
                    <p>Examples include yoga, Pilates, and stretching exercises.</p>
                </div>
                <div class="image exercise-images">
                    <img class="exercise-image" src="{{ url_for('static', filename='images/yoga_image.jpeg') }}">
                    <img class="exercise-image" src="{{ url_for('static', filename='images/pilates_image.jpeg') }}">
                    <img class="exercise-image" src="{{ url_for('static', filename='images/stretching_image.jpeg') }}">
                </div>
            </div>
        </div>
    </section>
    {% endif %}

    {% if section == 'balance' %}
    <section id="balance">
        <h2>Balance Exercises</h2>
        <div class="exercise">
            <div class="content-container">
                <div class="text-column">
                    <p>Balance exercises enhance stability and coordination.</p>
                    <p>Examples include Tai Chi, standing on one leg, and stability ball exercises.</p>
                </div>
                <div class="image exercise-images">
                    <img class="exercise-image" src="{{ url_for('static', filename='images/taichi_image.jpeg') }}">
                    <img class="exercise-image" src="{{ url_for('static', filename='images/one leg_image.jpeg') }}">
                    <img class="exercise-image" src="{{ url_for('static', filename='images/stabilityball_image.jpeg') }}">
                </div>
            </div>
        </div>
    </section>
    {% endif %}

    {% if section == 'core' %}
    <section id="core">
        <h2>Core Exercises</h2>
        <div class="exercise">
            <div class="content-container">
                <div class="text-column">
                    <p>Core exercises strengthen muscles in the abdomen, lower back, and pelvis.</p>
                    <p>Examples include planks, crunches, and leg raises.</p>
                </div>
                <div class="image exercise-images">
                    <img class="exercise-image" src="{{ url_for('static', filename='images/plank_image.jpeg') }}">
                    <img class="exercise-image" src="{{ url_for('static', filename='images/crunches_images.jpeg') }}">
                    <img class="exercise-image" src="{{ url_for('static', filename='images/legraises_image.jpeg') }}">
                </div>
            </div>
        </div>
    </section>
    {% endif %}

    {% if section == 'fitness-tips' %}
    <!-- Fitness Tips Section -->
    <section id="fitness-tips">
        <h2>Fitness Tips</h2>
        <div class="content-container">
            <div class="text-column">
                <h3>General Fitness Tips</h3>
                <ul>
                    <li>Stay Consistent: Consistency is key to seeing results in fitness.</li>
                    <li>Mix It Up: Incorporate different types of exercises.</li>
                    <li>Listen to Your Body: Pay attention to how your body feels.</li>
                    <li>Stay Hydrated: Drink plenty of water throughout the day.</li>
                    <li>Set Realistic Goals: Set achievable goals that motivate you.</li>
                </ul>

                <h3>Nutrition Tips</h3>
                <ul>
                    <li>Balance Your Plate: Aim for a balanced diet.</li>
                    <li>Pre-Workout Fuel: Eat a small meal or snack containing carbohydrates and protein.</li>
                    <li>Post-Workout Recovery: Refuel your body with protein and carbohydrates.</li>
                    <li>Stay Mindful of Portions: Pay attention to portion sizes.</li>
                </ul>
            </div>
        </div>
    </section>
    {% endif %}

    {% if section == 'expert-fitness-tips' %}
    <!-- Expert Fitness Tips Section -->
    <section id="expert-fitness-tips">
        <h2>Expert Fitness Tips and Advice</h2>
        <div class="content-container">
            <div class="text-column">
                <h3>Cardiovascular Fitness</h3>
                <ul>
                    <li>Interval Training: Incorporate HIIT into your cardio workouts.</li>
                    <li>Cross-Training: Mix different types of cardio exercises.</li>
                    <li>Heart Rate Monitoring: Use a heart rate monitor to gauge intensity levels.</li>
                </ul>

                <h3>Strength Training</h3>
                <ul>
                    <li>Progressive Overload: Gradually increase weight or resistance.</li>
                    <li>Proper Form: Focus on correct technique to prevent injuries.</li>
                    <li>Rest and Recovery: Allow muscles adequate time to recover.</li>
                </ul>

                <h3>Flexibility and Mobility</h3>
                <ul>
                    <li>Dynamic Stretching: Incorporate dynamic stretches.</li>
                    <li>Static Stretching: Perform static stretches after workouts.</li>
                    <li>Foam Rolling: Use a foam roller to release muscle tension.</li>
                </ul>
            </div>
        </div>
    </section>
    {% endif %}
</div>
{% endblock %}

Africode_Demo_Collaboration/app/templates/index.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
{% endblock %}

{% block content %}
<section class="hero">
    <h1>Welcome to Our Website</h1>
    <div class="image-container">
        <div class="image">
            <img class="pics-1" src="{{ url_for('static', filename='images/gyme.jpeg') }}" alt="Gym Image">
        </div>
    </div>
</section>
{% endblock %}

Africode_Demo_Collaboration/app/templates/nutrition.html
{% extends 'base.html' %}

{% block title %}Nutrition - FitPulse{% endblock %}

{% block content %}
<div class="container">
    <h1>Nutrition for Fitness</h1>
    <section class="nutrition-content">
        <div class="image">
            <img src="{{ url_for('static', filename='images/nutrition.jpg') }}" alt="Nutrition Image 1">
            <img src="{{ url_for('static', filename='images/nutrition2.jpg') }}" alt="Nutrition Image 2">
        </div>
        <p>Nutrition plays a crucial role in supporting your fitness goals. Eating a balanced diet with the right nutrients can help fuel your workouts, promote muscle recovery, and enhance overall performance.</p>

        <h2>Key components of a healthy diet for fitness include:</h2>
        <ul>
            <li>Lean proteins to support muscle growth and repair.</li>
            <li>Complex carbohydrates for sustained energy levels.</li>
            <li>Healthy fats for hormone production and overall health.</li>
            <li>Vitamins and minerals for proper bodily functions.</li>
            <li>Adequate hydration to maintain fluid balance and prevent dehydration.</li>
        </ul>
        
        <p>It's essential to tailor your nutrition to your specific fitness goals and individual needs. Consult with a nutritionist or dietitian for personalized advice and meal planning.</p>

        <h2>Pre-Workout Nutrition:</h2>
        <p>Consume a meal or snack rich in carbohydrates and proteins about 2-3 hours before your workout to provide sustained energy and support muscle recovery.</p>
        <p>Examples include a whole grain sandwich with lean meat, yogurt with fruit, or a smoothie with protein powder and oats.</p>

        <h2>Post-Workout Nutrition:</h2>
        <p>Eat a meal or snack containing proteins and carbohydrates within 30-60 minutes after your workout to replenish glycogen stores and aid muscle recovery.</p>
        <p>Examples include a protein shake with a banana, grilled chicken with quinoa and vegetables, or a tuna salad with whole grain crackers.</p>

        <h2>Hydration:</h2>
        <p>Drink water before, during, and after exercise to stay hydrated. For longer workouts, consider electrolyte drinks to replenish lost minerals.</p>

        <h2>Listen to Your Body:</h2>
        <p>Pay attention to how different foods affect your energy levels and performance. Adjust your diet based on your individual needs and fitness goals.</p>
    </section>
</div>
{% endblock %}

Africode_Demo_Collaboration/app/templates/testimonials.html
{% extends 'base.html' %}

{% block title %}Testimonials{% endblock %}

{% block content %}
<h1>Testimonials</h1>
<div class="section">
    <h2>What Our Users Say</h2>
    <div class="content-container">
        <div class="text-column">
            <p class="text-light">Hear from our satisfied users and their success stories.</p>
            <div class="testimonial">
                <p class="user"><strong>John Doe:</strong></p>
                <div class="image">
                    <img src="{{ url_for('static', filename='images/john.jpeg') }}" alt="Testimonials Image">
                </div>

                <p>"This platform has completely transformed my fitness journey! The workout plans are easy to follow and highly effective. I've seen significant improvements in my strength and endurance."</p>
            </div>

            <div class="testimonial">
                <p class="user"><strong>Jane Smith:</strong></p>
                <div class="image">
                    <img src="{{ url_for('static', filename='images/jane.jpeg') }}" alt="Testimonials Image">
                </div>
                <p>"The recipes provided are delicious and healthy. I've lost weight and feel more energetic. The community support is also amazing. Highly recommend this platform to anyone looking to get fit."</p>
            </div>


            <div class="testimonial">
                <p class="user"><strong>Mike Johnson:</strong></p>
                <div class="image">
                    <img src="{{ url_for('static', filename='images/mike.jpeg') }}" alt="Testimonials Image">
                </div>
                <p>
                    
                    "Great tools and resources for staying on track with my goals. The fitness gadgets section helped me find the perfect fitness tracker. Now, I can monitor my progress more effectively."</p>
            </div>
            <div class="testimonial">
                <p class="user"><strong>Sarah Williams:</strong></p>
                 <div class="image">
            <img src="{{ url_for('static', filename='images/sara.jpeg') }}" alt="Testimonials Image">
        </div>
                <p>"I love the flexibility exercises and yoga routines. They have significantly improved my posture and reduced my back pain. The detailed guides and videos are very helpful."</p>
            </div>


            <div class="testimonial">
                <p class="user"><strong>David Brown:</strong></p>
                <div class="image">
                    <img src="{{ url_for('static', filename='images/David.jpeg') }}" alt="Testimonials Image">
                </div>
                <p>"The platform offers excellent workout plans for all fitness levels. As a beginner, I found the step-by-step instructions very useful. I've gained more confidence and strength."</p>
            </div>
        </div>
       
    </div>
</div>
{% endblock %}